### ISSUE TITLE
Links not added in spec/examples

### ISSUE THREAD

**Issue by rjalander** [cdevents/spec#212]
Links are not created for any of the [spec/examples](https://github.com/cdevents/spec/tree/main/examples), but they have schemaUri and chain_id, it's good to have links too for validation.

**Comment by afrittoli** [comment]
Thanks @rjalander - we are aware of this, @xibz planned examples to be added as a follow-up.

**Comment by afrittoli** [comment]
Perhaps we could add at least empty link lists to all examples `links: []` which will help trigger better validation.

**Comment by afrittoli** [comment]
We discussed this with @xibz today. Having links in the examples is very beneficial for validation, but confusing for end-users because examples are not associated with a specific use case and thus those links are not meaningful. 

To solve the issue, I will rename `examples` to `conformance`, and add the links to the JSON files in there.
We'll then build over time a proper set of examples. See more details in https://github.com/cdevents/spec/issues/217
